version: '3'

services:
  php-fpm:
    build: ./php-fpm
    container_name: app-php-fpm
    working_dir: /app
    ports:
      - "9000:9000"
    volumes:
      - ./../:/app:rw,cached
    env_file:
      - ../.env
    depends_on:
      - db
      - rabbitmq
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: app-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  db:
    image: postgres:11
    container_name: app-db
    restart: always
    environment:
        - POSTGRES_DB=app
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
    ports:
        - 5432:5432
