version: '3'

services:
  php-fpm:
    build: ./php-fpm
    container_name: app_php_fpm
    working_dir: /app
    ports:
      - "9000:9000"
    volumes:
      - ./../:/app:rw,cached
    env_file:
      - ../.env
    depends_on:
      - db
      - rabbitmq
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: app_rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  db:
    image: postgres:11
    container_name: app_db
    restart: always
    env_file:
      - ../.env
    ports:
      - 5432:5432
